name: Build and Upload Executable on setup.py Change

on:
  push:
    branches:
      - main
    paths:
      - 'setup.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_upload:
    runs-on: windows-latest  # 使用 Windows 系统来构建
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install tsugu
          pip install git+https://github.com/LagrangeDev/lagrange-python@broken

      - name: Build executable
        run: |
          pyinstaller --onefile your_script.py
          VERSION=$(python setup.py --version)
          mv ./dist/your_script.exe ./dist/tsugu-Windows-amd64-${VERSION}.exe
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Upload executable to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.repository.releases[0].upload_url }}
          asset_path: ./dist/tsugu-Windows-amd64-${{ env.VERSION }}.exe  # 更新文件路径和名称
          asset_name: tsugu-Windows-amd64-${{ env.VERSION }}.exe  # 更新文件名
          asset_content_type: application/x-msdownload
