name: Build and Upload Executable on setup.py Change

on:
  push:
    branches:
      - main
    paths:
      - 'version.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_upload:
    runs-on: windows-latest  # 使用 Windows 系统来构建
    env:
      PYTHONUTF8: 1  # 设置 UTF-8 编码环境变量
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set VERSION environment variable
        run: |
          $VERSION = Get-Content version.txt
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
      - name: Print VERSION
        run: |
          echo "VERSION=${{ env.VERSION }}"
          
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pyinstaller
      #     pip install tsugu
      #     pip install tarina
      #     pip install git+https://github.com/LagrangeDev/lagrange-python@broken
          
      # - name: Build executable
      #   run: |
      #     pyinstaller --onefile bot/__main__.py --icon=./ico.ico





      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install tsugu
          pip install tarina
          pip install git+https://github.com/LagrangeDev/lagrange-python@broken
      
      - name: Build executable
        run: |
          python -m nuitka --standalone --onefile --assume-yes-for-downloads --output-dir=./dist bot/__main__.py
      
      
      


      
      - name: Rename executable file
        run: |
          mv ./dist/__main__.exe ./dist/tsugu-Windows-amd64-${{ env.VERSION }}.exe

      - name: Create GitHub Release
        id: create_release  # 加上这个id
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
  
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 确保这里使用了上面设置的id
          asset_path: ./dist/tsugu-Windows-amd64-${{ env.VERSION }}.exe  # 更新文件路径和名称
          asset_name: tsugu-Windows-amd64-${{ env.VERSION }}.exe  # 更新文件名
          asset_content_type: application/x-msdownload
